
default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  username: <%= ENV["API_DATABASE_USER"] %>
  password: <%= ENV["API_DATABASE_PASSWORD"] %>
  host: <%= ENV["API_DATABASE_HOST"] %>
  port: <%= ENV["API_DATABASE_PORT"] { 5432 } %>

development:
  <<: *default
  database: api_development

test:
  <<: *default
  database: api_test

production:
  <<: *default
  database: api_production
