services:
  db:
    image: postgres:14-alpine
    ports:
      - 5433:5432
    volumes:
      - ~/apps/postgres-bc:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD=griffin
      - POSTGRES_USER=griffin