source "https://rubygems.org"

ruby "3.2.3"

gem "rails", "~> 7.1.3", ">= 7.1.3.2"
gem "pg", "~> 1.1"
gem "puma", ">= 5.0"
gem "tzinfo-data", platforms: %i[ windows jruby ]
gem 'dotenv'
gem 'bcrypt', '~> 3.1.7'
gem 'jwt'
gem 'rack-cors', :require => 'rack/cors'

gem "bootsnap", require: false
group :development, :test do
  gem "debug", platforms: %i[ mri windows ]
end
